
# get all pizzas
get https://pizza-api.projectcodex.net/api/pizzas 

# create cart
get https://pizza-api.projectcodex.net/api/pizza-cart/create?username=tswelo


# view cart
get https://pizza-api.projectcodex.net/api/pizzas/username/tswelo


# view user's cart
get https://pizza-api.projectcodex.net/api/pizza-cart/username/tswelo


# view featured pizzas
get https://pizza-api.projectcodex.net/api/pizzas/featured?username=tswelo


#post featured pizzas 
post https://pizza-api.projectcodex.net/api/pizzas/featured
{
	"username" : "tswelo",
	"pizza_id" : 1
}


# add pizza to cart
POST https://pizza-api.projectcodex.net/api/pizzas/api/pizza-cart/add

{
	"cart_code" : "qS5prSWJVQ",
	"pizza_id" : 3

}


#  remove pizza from cart
post https://pizza-api.projectcodex.net/api/pizzas/api/pizza-cart/remove

{
	"cart_code" : "qS5prSWJVQ",
	"pizza_id" : 3

}


# view cart content
GET https://pizza-api.projectcodex.net/api/pizza-cart/:cart_code/get


# make payments
post https://pizza-api.projectcodex.net/api/pizza-cart/pay
{
	"cart_code" : "qS5prSWJVQ",
	"amount" : 300

}


